name: Bug Report
description: Report a bug to help improve the application
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the problem.
      placeholder: What is going wrong?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Expected result...
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
      placeholder: Actual result...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs / error messages
      description: Paste any relevant logs or error messages.
      render: shell
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser (if relevant), and Node version.
      placeholder: "Ubuntu 22.04, Chrome 120, Node 20.11.0"
    validations:
      required: false
